### ISSUE TITLE
DB Server

### ISSUE THREAD

**Issue by wesleyvicthor** [Aeronautics/Spitfire#10]
Será que não rola jogar a base no server ?
Assim fica tudo centralizado é mais fácil para sabermos o que ta rolando.

**Comment by alganet** [comment]
Eu também prefiro. Minha conexão aqui em casa tá um lixo e mal consigo trabalhar, o @augustohp tem acesso ao painel do Linode pra configurar as paradas. Também posso te dar acesso ssh, me pinga no gtalk.

A gente subiu o repositório em http://datagov.net.br/ mas não configurou nada.

**Comment by augustohp** [comment]
@wesleyvicthor A base também tá no repositório GIT. Pelo fato de não ter uma conexão decente em casa eu nem cogito usar uma base de dados remota, mas é possível. Se quiser eu configuro pra você lá.

Mas da pra usar o _Mysql Workbench_ também pra manter a base atualizada. A MER ta no `/doc` do repositório.

**Comment by wesleyvicthor** [comment]
Sim eu vi.
De boa, ja rodei a base aqui.
Apenas sugeri caso ajudasse a todos, mas se vocês tem esse problema, forgeta (:

Quanto ao SQL rodei direto e deu pau nas duas ultima tabelas...

obs: Por que o Relational precisa persistir dados que ja foram persistidos ? (ex: Update)

**Comment by augustohp** [comment]
@wesleyvicthor: Que pau deu? Você fez um Forward ou um Sync?

Quanto ao lance de persistir dados já persistidos funciona assim: na primeira persistência (que só acontece quando o cara não é encontrado) criamos o cara na base, na segunda garantimos a atualização dos dados do cara segundo os dados do `miner` (mesmo que ele tenha acabado de ser inserido).

Nada elegante, mãs.... é o que tem pra hoje.

**Comment by wesleyvicthor** [comment]
Cara se não meu engano o erro foi por algum motivo das constraints/fks não tenho certeza, apenas não rodou.
Não estou usando o WB.

hhahaha. ok.
Tem alguns pontos que seria interessante uma issue...
Tentei definir o timestamp definindo a propriedade usando: new DateTime('now');
O que entendi foi que o Relational acha que esse cara é uma entity e tenta pegar o id dele, triste isso.

**Comment by augustohp** [comment]
Cara, eu tirei todos os TIMESTAMP e coloquei DATETIME... e to usando `date()` mesmo pra inserir. O Relational n suporta mesmo essa conversão, abre a issue ;)

**Comment by augustohp** [comment]
Estou fechando essa tarefa. 
Apenas pra deixar claro nosso workflow atual de prioridades para manter nossos bancos locais e da base oficial todos sincronizados:
1. Manter a MER (localizada em `/doc/spitfire.mwb`) em **Mysql Workbench** antes de mais nada
2. Manter o arquivo SQL (`/doc/spitfire.sql`) de acordo com a MER acima

É interessante também ver o relacionamento disso com a Issue #11.

**Comment by wesleyvicthor** [comment]
Ok, apenas certificar que tanto via WB quanto o arquivo .sql não terão erros de execução.
