### ISSUE TITLE
Salvar DUMP em XML no repositório

### ISSUE THREAD

**Issue by henriquemoody** [Aeronautics/Spitfire#11]
A gente pode salvar e carregar um dump do mysql em formato XML.

```
mysqldump -X hackathon > hackathon.xml
```

```
mysql -X hackathon < hackathon.xml
```

O que acham?

**Comment by augustohp** [comment]
Perfeito. Ainda mais pra guardar os dados que devem ser levados na base... acho que alguns desses dados são:
- Esferas
- Mandatos
- Partidos

Será que não é bacana também fazer um _target_ específico no `Makefile` pra isso?

**Comment by henriquemoody** [comment]
Seria uma boa mesmo esse lance do _target_ no `Makefile`, mas ao atualizar o Foundation a gente não perderia o trampo?

**Comment by alganet** [comment]
A gente pode incluir outros makefiles, inclusive usando patterns:

http://www.gnu.org/savannah-checkouts/gnu/make/manual/html_node/Include.html

Um pattern comum é ter vários Makefiles, `Makefile.project`, `Makefile.database`, etc e incluir eles no makefile principal. Adicionar suporte a isso no Foundation é fácil.

**Comment by henriquemoody** [comment]
Tilango
