### ISSUE TITLE
Implementar dbdeploy para atualização de banco de dados.

### ISSUE THREAD

**Issue by henriquemoody** [Aeronautics/Spitfire#14]
Atualização de banco de dados já foi um problema pra gente nesse pequeno tempo de projeto. 
O que vocês acham de usar uma forma mais inteligente de atualizar o banco de dados?

http://davedevelopment.co.uk/2008/04/14/how-to-simple-database-migrations-with-phing-and-dbdeploy.html

**Comment by alganet** [comment]
Parece maneiro o dbdeploy, embora ele seja em java :S Eu não sou familiar com nenhum sistema de migrations, mas boto fé de começarmos a usar!

Também não sei em relação ao Phing, eu prefiro o makezão =) Mas não me oponho nem vou ficar incomodado se alguém quiser usar.
