### ISSUE TITLE
Padronizar formato de nomes no banco de dados

### ISSUE THREAD

**Issue by henriquemoody** [Aeronautics/Spitfire#16]
Os nomes no banco de dados estão usando diversos _cases_, por exemplo:
- PARTIDO TRABALHISTA BRASILEIRO
- Partido Democrático Trabalhista
- Partido da Mobilização Nacional

O melhor seria alterar o _case_ dessas strings para que fiquem assim:
- Partido Trabalhista Brasileiro
- Partido Democrático Trabalhista
- Partido Da Mobilização Nacional

Ou criar uma regra para que somente os artigos (http://pt.wikipedia.org/wiki/Artigo_(gramática)) estejam com letras minúsculas.

**Comment by alganet** [comment]
Isso é bem irritante =/ Inicialmente acho que um ucwords() resolveria mesmo como você sugeriu. 

+1
