### ISSUE TITLE
Documentar fontes de dados

### ISSUE THREAD

**Issue by augustohp** [Aeronautics/Spitfire#17]
Podemos usar o Wiki como um local a fim de documentar fontes de dados interessantes, e que podem ser usadas por todo mundo contribuindo com o projeto. O que acham?

Algumas fontes de dados que já usamos são:
- [Câmara Municipal de São Paulo](http://www.camara.sp.gov.br/index.php?option=com_wrapper&view=wrapper&Itemid=219)
- [dados.gob.br](http://dados.gov.br/)

**Comment by henriquemoody** [comment]
Criei o a página na [Wiki](https://github.com/Aeronautics/Spitfire/wiki/Fontes-de-dados) pra gente listas as fontes de dados existentes.
=]
